server:
  port: 9999

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: [eureka-server의 주소]

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: [GIT 주소]
          default-label: master
          ignore-local-ssh-settings: true
          username: ${GIT_ID}
          password: ${GIT_PW}

  rabbitmq:
    host: localhost
    port: 5672
    username: lostinfrost
    password: c101

management:
  endpoints:
    web:
      exposure:
        include: health, bus-refresh